name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3' # Specify your Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
         path: /opt/hostedtoolcache/flutter
         key: flutter-dependencies-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
         restore-keys: |
                   flutter-dependencies-${{ runner.os }}-

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release